Revert "Revert "Pin to awestruct 0.5.6 since 0.5.7 introduces a Ruby 2.0 dependency""
This reverts commit ec1cde16bdca4f222671f51cd8c2e8d43df1a47e.

This is an attempt to clear up the issue we're seeing in ci.jenkins-ci.org
(only) where the build is failing due to errors like:

    An error during rendering /blog/2010/2010-02-10-keeping-your-configuration-and-data-in-subversion.md occurred.
    While processing file /files/jenkins/slave-workspace/jenkins.io/master/content/blog/2010/2010-02-10-keeping-your-configuration-and-data-in-subversion.md
    An error occurred: undefined method `parse' for Kramdown:Module
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/kramdown-1.9.0/lib/kramdown/document.rb:107:in `initialize'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt/kramdown.rb:12:in `prepare'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt/template.rb:89:in `initialize'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt/mapping.rb:136:in `new'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/tilt-2.0.2/lib/tilt.rb:43:in `new'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.7/lib/awestruct/handlers/base_tilt_handler.rb:131:in `rendered_content'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.7/lib/awestruct/handlers/layout_handler.rb:47:in `rendered_content'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.7/lib/awestruct/page.rb:143:in `rendered_content'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.7/lib/awestruct/engine.rb:427:in `generate_page'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/awestruct-0.5.7/lib/awestruct/engine.rb:403:in `block in generate_output'
    org/jruby/RubyProc.java:318:in `call'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:408:in `call_with_index'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:288:in `block in work_in_threads'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:419:in `with_instrumentation'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:287:in `block in work_in_threads'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/parallel-1.6.2/lib/parallel.rb:183:in `block in in_threads'
    org/jruby/RubyProc.java:318:in `call'
    /files/jenkins/slave-workspace/jenkins.io/master/build/tmp/asciidoctor/gems/logging-2.0.0/lib/logging/diagnostic_context.rb:448:in `block in create_with_logging_context'