Update shared-libraries.adoc
Example pipeline snippet failed with following when executed at Jenkins 

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: 5: Undefined section "stage" @ line 5, column 5.
       stage ('Example') {
       ^
WorkflowScript: 3: Missing required section "stages" @ line 3, column 1.
   pipeline {
   ^

Fix- Added the Stages{} in example pipeline snippet