Updated node docker image version
node:7-alpine tag is not supported any more, see the Docker Hub for more details: https://hub.docker.com/_/node

As of 7 July 2020 the first example of Pipeline execution fails:

[Pipeline] sh
+ docker inspect -f . node:7-alpine
Error: No such image or container: node:7-alpine
[Pipeline] sh
+ docker pull node:7-alpine
Pulling repository node
Get https://index.docker.io/v1/repositories/library/node/images: dial tcp 3.220.75.233:443: connection timed out